#!/bin/sh
# Compile and run the NotesTests suites on the Mac, without a simulator.
#
# `xcodebuild test` needs an iOS platform this machine may not have, and CI is
# the authority either way. But almost all of Notes/Logic is plain Foundation,
# EventKit, Speech or FoundationModels code that builds for macOS, so the
# repo's own XCTest files can be driven directly with the stand-ins in
# scripts/puretests/Shim.swift. That is the red-green loop: seconds, not
# minutes, and no simulator.
#
#   scripts/pure-tests.sh            # every suite
#   scripts/pure-tests.sh Insertion  # only suites whose name contains that
#
# It does NOT replace CI. Nothing here compiles a SwiftUI view, a SwiftData
# model or a widget, so a green run is necessary and not sufficient.
set -eu
cd "$(dirname "$0")/.."

FILTER="${1:-}"
BUILD="${TMPDIR:-/tmp}/matte-pure-tests"
mkdir -p "$BUILD"
PLUGINS="$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins"

# Four files cannot build for macOS at all: ActivityKit has no Mac, a
# LiveActivityIntent cannot exist there, and AVAudioSession is iOS-only. None
# of them has a suite, because none of them is pure logic: SpeechListener is
# the microphone itself and is only ever proved on a device.
SOURCES=$(find Notes/Logic -name '*.swift' \
    ! -name 'PinActivity.swift' \
    ! -name 'PinnedNoteAttributes.swift' \
    ! -name 'StepCounterIntent.swift' \
    ! -name 'SpeechListener.swift')

# The suites are compiled as plain sources against the stand-ins, so the two
# imports that only mean something inside an Xcode test bundle are rewritten
# on the way into the build directory. The files in git are untouched.
rm -rf "$BUILD/suites" && mkdir -p "$BUILD/suites"
for f in $(find NotesTests -name '*.swift' | sort); do
    sed -e 's/^import XCTest$/import Foundation/' \
        -e '/^@testable import Notes$/d' \
        "$f" > "$BUILD/suites/$(basename "$f")"
done
TESTS=$(find "$BUILD/suites" -name '*.swift' | sort)

python3 - "$BUILD/main.swift" "$FILTER" $TESTS <<'PY'
import re, sys

out_path, flt, *test_files = sys.argv[1:]
suites, skipped = [], []

for path in test_files:
    src = open(path).read()
    classes = re.findall(r'^\s*(?:final\s+)?class\s+(\w+)\s*:\s*XCTestCase\b', src, re.M)
    if len(classes) != 1:
        sys.exit(f"{path}: expected exactly one XCTestCase, found {len(classes)}. "
                 "The generator assumes one suite per file; teach it otherwise.")
    name = classes[0]
    if flt and flt.lower() not in name.lower():
        skipped.append(name)
        continue
    # No-argument test methods, sync or async, throwing or not. Anything
    # that takes an argument is not an XCTest test.
    methods = re.findall(r'^\s*func\s+(test\w*)\s*\(\s*\)', src, re.M)
    if methods:
        suites.append((name, methods))

lines = [
    "// Generated by scripts/pure-tests.sh. Do not edit, do not commit.",
    "import Foundation",
    "",
    "let suites: [(String, [(String, () async throws -> Void)])] = [",
]
for name, methods in suites:
    lines.append(f"    (\"{name}\", {{ let t = {name}(); return [")
    for m in methods:
        lines.append(f"        (\"{m}\", t.{m}),")
    lines.append("    ] }()),")
lines += [
    "]",
    "",
    "var run = 0",
    "var failedTests: [String] = []",
    "",
    "// An async test needs somewhere to be awaited, and top-level code is",
    "// not that place, so the whole run happens inside one task.",
    "func runEverything() async {",
    "    for (suite, tests) in suites {",
    "        for (name, body) in tests {",
    "            let mark = PureTestRun.shared.count",
    "            PureTestRun.shared.currentTest = \"\\(suite).\\(name)\"",
    "            run += 1",
    "            do { try await body() } catch {",
    "                PureTestRun.shared.record(\"threw \\(error)\", #filePath, #line)",
    "            }",
    "            if PureTestRun.shared.count > mark { failedTests.append(\"\\(suite).\\(name)\") }",
    "        }",
    "    }",
    "}",
    "",
    "let finished = DispatchSemaphore(value: 0)",
    "Task { await runEverything(); finished.signal() }",
    "finished.wait()",
    "",
    "for failure in PureTestRun.shared.failures { print(\"  ✗ \\(failure)\") }",
    "print(\"\")",
    "if failedTests.isEmpty {",
    "    print(\"\\(run) tests in \\(suites.count) suites, all passed\")",
    "} else {",
    "    print(\"\\(run) tests in \\(suites.count) suites, \\(failedTests.count) failed:\")",
    "    for name in failedTests { print(\"    \\(name)\") }",
    "    exit(1)",
    "}",
]
open(out_path, "w").write("\n".join(lines) + "\n")

total = sum(len(m) for _, m in suites)
print(f"{total} tests in {len(suites)} suites"
      + (f" ({len(skipped)} suites filtered out)" if skipped else ""))
PY

swiftc -O -swift-version 5 -enable-bare-slash-regex \
    -plugin-path "$PLUGINS" \
    -o "$BUILD/puretests" \
    $SOURCES $TESTS scripts/puretests/Shim.swift "$BUILD/main.swift"

exec "$BUILD/puretests"
